### ISSUE TITLE
How to receive outputs into types other than tensors (maps, sequences)?

### ISSUE THREAD

**Issue by IndiTheo** [yalue/onnxruntime_go_examples#5]
I'm new to ONNX, but something is unclear to me with the API.
I have an ONNX that goes like:
```
output {
    name: "output_label"
    type {
      tensor_type {
        elem_type: 7
        shape {
          dim {
          }
        }
      }
    }
  }
  output {
    name: "output_probability"
    type {
      sequence_type {
        elem_type {
          map_type {
            key_type: 7
            value_type {
              tensor_type {
                elem_type: 1
              }
            }
          }
        }
      }
    }
  }
}
```

So the output type should be a sequence of maps from Int64 to Float32?
How to receive this output in GO?

```
session, err := ort.NewAdvancedSession("onnx/models/model.onnx",
		[]string{"float_input"}, []string{"output_label", "output_probability"},
		[] ?______________________________________?, nil)
	defer session.Destroy()
```

Thank you

Reposted here:
https://github.com/yalue/onnxruntime_go/issues/57

**Comment by yalue** [comment]
Yes, sorry about that!  But the current library does not support other `OrtValue` types apart from tensors.  I'd like to say that I will add support in the future, but it would be quite a bit of a work, so "not planned" is unfortunately an appropriate status for now.
