### ISSUE TITLE
I had an exception when using the other onnx.

### ISSUE THREAD

**Issue by marlin2024** [yalue/onnxruntime_go_examples#8]
1. I found onnx_list_inputs_and_outputs and tried to fetch mnist.onnx, from which I found a few lines of configuration that I needed to change, so I tried to modify the file
```shell
➜  onnx_list_inputs_and_outputs git:(master) ✗ ./onnx_list_inputs_and_outputs --onnx_file=../mnist/mnist.onnx
1 inputs to ../mnist/mnist.onnx:
  Index 0: Tensor "Input3": [1 1 28 28], ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT
1 outputs from ../mnist/mnist.onnx:
  Index 0: Tensor "Plus214_Output_0": [1 10], ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT
➜  onnx_list_inputs_and_outputs git:(master) ✗ ./onnx_list_inputs_and_outputs --onnx_file=common.onnx        
1 inputs to common.onnx:
  Index 0: Tensor "input1": [1 1 64 -1], ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT
1 outputs from common.onnx:
  Index 0: Tensor "387": [1 -1], ONNX_TENSOR_ELEMENT_DATA_TYPE_FLOAT
➜  onnx_list_inputs_and_outputs git:(master) ✗ 
```
2. diff as follows, but it not work
<img width="1287" alt="image" src="https://github.com/user-attachments/assets/08c47475-049f-4c0e-bd66-01f2e4526559">

The error message is as follows
```shell
➜  mnist git:(master) ✗ go run *.go
Saved postprocessed input image to ./postprocessed_input_image.png.
Error running network: Error creating input tensor: Invalid tensor shape: Dimension 3 of the shape has invalid value -1
exit status 1
```
3. now i  try to change `inputShape := ort.NewShape(1, 1, 64, -1)`  -> `inputShape := ort.NewShape(1, 1, 64, 28)`, but it still not work
```shell
Saved postprocessed input image to ./postprocessed_input_image.png.
Error running network: Error creating input tensor: The tensor's shape ([1 1 64 28]) requires 1792 elements, but only 784 were provided
exit status 1
```
4. the common.onnx file I download form `https://github.com/sml2h3/ddddocr/blob/master/ddddocr/common.onnx`

I would like to know how to solve this problem, thank you very much!

**Comment by yalue** [comment]
It looks like you already discovered this, but it's true that `onnxruntime_go` is not capable of inferring shape dimensions.  That aside, I do not know what `common.onnx` is supposed to do, as I am unable to read the documentation in the associated repo, sorry!

Speaking generally: what are the inputs and outputs supposed to be?  Why would you expect the ONNX input image to be the correct input?  The input images in the MNIST example are in the format expected by `mnist.onnx`: a 28x28 floating-point grayscale image (requiring 784 floats in total).  It looks like you tried to create a tensor with a different shape but the same data, so it's not surprising that it won't work.  You'll need to provide data in the correct format along with the shape.  Providing a different shape does not change the data slice, which still contains the MNIST input.

I often recommend this, but I often find it easier to quickly write a python test using the python `onnxruntime` library.  If you can write a python test that correctly runs `common.onnx`, but are unable to reproduce the same outputs using the go wrapper despite using identical input data then an issue is more likely.

Currently, this does not seem like an issue with the example, but with missing fundamentals of running a .onnx network.  Learning to use `onnxruntime` in python should be a much easier introduction.  Feel free to re-open this issue if you have a _working_ python script that performs as expected but are unable to reproduce the correct behavior in Go.
