### ISSUE TITLE
How to parse the output of yolov8x-seg

### ISSUE THREAD

**Issue by hykyle** [yalue/onnxruntime_go_examples#9]

**Comment by yalue** [comment]
I apologize, but issues here are not the place to ask for "homework help."  Please learn to use the network using `onnxruntime` in python, and feel free to reopen this issue if you have a _working_ python example that you are unable to replicate in Go.  These examples are intended to illustrate using `.onnx` files via the `onnxruntime_go` wrapper, and not intended to instruct how to use `.onnx` networks in general.
